HelloCook/HelloCook/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from HelloCook import views
from django.views.generic import TemplateView

urlpatterns = [
    # path('', views.index, name='index'),
    path('', TemplateView.as_view(template_name="home.html"), name='home'),
    path('home/', TemplateView.as_view(template_name="home.html"), name='home'), 
    path('account/', include('account.urls')),
    path('article/', include('article.urls')),
    path('admin/', admin.site.urls),
]

HelloCook/account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'  

urlpatterns = [
    # path(r'login/', views.user_login, name='user_login'),
    path(r'login/', auth_views.LoginView.as_view(template_name="account/login.html"), name='user_login'),  # Use Django's built-in login methods
    path(r'loginout/', auth_views.LogoutView.as_view(template_name="account/logout.html"), name='user_logout'),  # Use Django's built-in logout methods
    path(r'register/', views.user_register, name='user_register'),
    path('password-change/', auth_views.PasswordChangeView.as_view(template_name="account/password_change_form.html",
        success_url="/account/password-change-done/"), name='password_change'),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(
        template_name="account/password_change_done.html"), name='password_change_done'),
    path('my-information/', views.myself, name='my_information'),
    path('edit-my-information/', views.myself_edit, name="edit_my_information"),
    path('my-image/', views.my_image, name="my_image"),
]

HelloCook/article/urls.py
from django.urls import path
from . import views, list_views
from django.urls import re_path

app_name = 'article'  

urlpatterns = [
    path('article-column/', views.article_column, name="article_column"),
    path('rename-article-column/', views.rename_article_column, name="rename_article_column"),
    path('del-article-column/', views.del_article_column, name="del_article_column"),
    path('article-post/', views.article_post, name="article_post"),
    path('article-list/', views.article_list, name="article_list"),
    re_path('article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"),
    path('del-article/', views.del_article, name="del_article"),
    path('redit-article/<int:article_id>/', views.redit_article, name="redit_article"),
    path('list-article-titles/', list_views.article_titles, name="article_titles"),
    path('article-content/<int:id>/<slug:slug>/', list_views.article_detail, name="article_content"),
    path('list-article-titles/<username>/', list_views.article_titles, name="author_articles"),
    path('like-article/', list_views.like_article, name="like_article"),
    path('view-article/', list_views.view_article, name="view_article"),
]

HelloCook/article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from slugify import slugify


class ArticleColumn(models.Model):
    user = models.ForeignKey(User, related_name='article_column', on_delete=models.CASCADE)
    column = models.CharField(max_length=200)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.column


class ArticlePost(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="article")
    title = models.CharField(max_length=200)
    abstract = models.CharField(max_length=200)
    slug = models.SlugField(max_length=500)
    column = models.ForeignKey(ArticleColumn, on_delete=models.CASCADE, related_name="article_column")
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    users_like = models.ManyToManyField(User, related_name="articles_like", blank=True)
    users_view = models.ManyToManyField(User, related_name="articles_view", blank=True)

    class Meta:
        ordering = ("-updated",)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.title

    def save(self, *args, **kargs):
        self.slug = slugify(self.title)
        super(ArticlePost, self).save(*args, **kargs)

    def get_absolute_url(self):
        return reverse("article:article_detail", args=[self.id, self.slug])

    def get_url_path(self):
        return reverse("article:article_content", args=[self.id, self.slug])

class Comment(models.Model):
    article = models.ForeignKey(ArticlePost, on_delete=models.CASCADE, related_name="comments")
    commentator = models.CharField(max_length=90)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return "Comment by {0} on {1}".format(self.commentator.username, self.article)

HelloCook/article/forms.py
from django import forms
from .models import ArticleColumn
from .models import ArticlePost
from .models import Comment


class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ("column",)

class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ("title", "abstract", "body")

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("commentator", "body",)

HelloCook/article/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from .models import ArticleColumn
from .forms import ArticleColumnForm
from .forms import ArticlePostForm
from django.views.decorators.http import require_POST
from .models import ArticlePost, Comment
from .forms import CommentForm
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


@login_required(login_url='/account/login/')
@csrf_exempt
def article_column(request):
    if request.method == "GET":
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form = ArticleColumnForm()
        return render(request, "article/column/article_column.html", {"columns": columns, 'column_form': column_form})

    if request.method == "POST":
        column_name = request.POST['column']
        columns = ArticleColumn.objects.filter(user_id=request.user.id, column=column_name)
        if columns:
            return HttpResponse('2')
        else:
            ArticleColumn.objects.create(user=request.user, column=column_name)
            return HttpResponse("1")


@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def rename_article_column(request):
    column_name = request.POST["column_name"]
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.column = column_name
        line.save()
        return HttpResponse("1")
    except:
        return HttpResponse("0")


@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article_column(request):
    column_id = request.POST["column_id"]
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")


@login_required(login_url='/account/login')
@csrf_exempt
def article_post(request):
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data
            try:
                new_article = article_post_form.save(commit=False)
                new_article.author = request.user
                new_article.column = request.user.article_column.get(id=request.POST['column_id'])
                new_article.save()
                return HttpResponse("1")
            except:
                return HttpResponse("2")
        else:
            return HttpResponse("3")
    else:
        article_post_form = ArticlePostForm()
        article_columns = request.user.article_column.all()
        return render(request, "article/column/article_post.html",
                      {"article_post_form": article_post_form, "article_columns": article_columns})


@login_required(login_url='/account/login')
def article_list(request):
    articles_list = ArticlePost.objects.filter(author=request.user)
    paginator = Paginator(articles_list, 10)
    page = request.GET.get('page')
    try:
        current_page = paginator.page(page)
        articles = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
        articles = current_page.object_list
    return render(request, "article/column/article_list.html", {"articles": articles, "page": current_page})


# @login_required(login_url='/account/login')
# def article_detail(request, id, slug):
#     article = get_object_or_404(ArticlePost, id=id, slug=slug)
#     return render(request, "article/column/article_detail.html", {"article": article})


@login_required(login_url='/account/login')
def article_detail(request, id, slug):
    article = get_object_or_404(ArticlePost, id=id, slug=slug)

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.article = article
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, "article/list/article_content.html",
                  {"article": article, "comment_form": comment_form})


@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article(request):
    article_id = request.POST['article_id']
    try:
        article = ArticlePost.objects.get(id=article_id)
        article.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")


@login_required(login_url='/account/login')
@csrf_exempt
def redit_article(request, article_id):
    if request.method == "GET":
        article_columns = request.user.article_column.all()
        article = ArticlePost.objects.get(id=article_id)
        this_article_form = ArticlePostForm(initial={"title": article.title})
        this_article_column = article.column
        return render(request, "article/column/redit_article.html",
                      {"article": article, "article_columns": article_columns, "this_article_column": this_article_column, "this_article_form": this_article_form})
    else:
        redit_article = ArticlePost.objects.get(id=article_id)
        try:
            redit_article.column = request.user.article_column.get(id=request.POST['column_id'])
            redit_article.title = request.POST['title']
            redit_article.abstract = request.POST['abstract']
            redit_article.body = request.POST['body']
            redit_article.save()
            return HttpResponse("1")
        except:
            return HttpResponse("2")

HelloCook/templates/article/list/article_content.html
{% extends "base.html" %}
{% load article_tags %}
{% load staticfiles %}
{% block title %} articles content {% endblock %}
{% block content %}

{% with total_likes=article.users_like.count users_like=article.users_like.all %}

<div class="container">
    <div class="col-md-9">
        <header>
            <h1>{{ article.title }}</h1>
            <p>
                <a href="{% url 'article:author_articles' article.author.username %}">{{ article.author.username }}</a>
                <span style="margin-left:20px" class="glyphicon glyphicon-thumbs-up">{{ total_likes }}like{{ total_likes|pluralize }}</span>
                {% comment %} <span style="margin-left:20px">{% article_total_views article.id %} views</span> {% endcomment %}
            </p>
        </header>

        <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}" />
        <div id='editormd-view'>
            <textarea id="append-test" style="display:none;">
{{ article.body }}
        </textarea>
        </div>
        <div>
            <p class="text-center">
                <a onclick="like_article({{article.id}}, 'like')" href="#">
                    <span class="glyphicon glyphicon-thumbs-up">like</span>
                </a>
                <a onclick="like_article({{article.id}}, 'unlike')" href="#">
                    <span style="margin-left: 15px;" class="glyphicon glyphicon-thumbs-down" >unlike</span>
                </a>
            </p>
        </div>
        <br>
        <div>
            <p class="text-center"><strong>Who like this article</strong></p>
            {% for user in article.users_like.all %}
            <p class="text-center">{{user.username}}</p>
            {% empty %}
            <p class="text-center">Be the first to like this article</p>
            {% endfor %}
        </div>
        <div>
            <h3><span class="glyphicon glyphicon-bullhorn"></span>This article has {{ comments.count }} comments:</h3>
            {% for comment in article.comments.all %}
            <div>
                <p><strong>{{ comment.commentator }}</strong>said:</p>
                <p style="margin-left:40px;">{{ comment.body }}</p>
            </div>
            {% empty %}
            <p>Be the first to comment!</p>
            {% endfor %}

            <br>
            <h3><span class="glyphicon glyphicon-send"></span>Leave your comment.</h3>
            <form action="." method="post" class="form-horizontal" role="form">{% csrf_token %}
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Title</label>
                    <div class="col-sm-10">
                        {{ comment_form.commentator}}
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Content</label>
                    <div class="col-sm-10">
                        {{ comment_form.body }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <p><input type="submit" name="" value=" comment " class="btn btn-primary"></p>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="col-md-3">
        <p class="text-center">
            <h3>Most liked articles</h3>
        </p>
        {% most_liked_articles 3 %}
        <hr>

        <p class="text-center">
            <h3>Latest Articles</h3>
        </p>
        {% latest_articles 3 %}
        <hr>

         <p class="text-center">
        <h3>Most commented articles.</h3></p>
        {% most_commented_articles as most_comments %}
        <ul>
            {% for comment_article in most_comments %}
            <li>
                <a href="{{comment_article.get_url_path}}">{{ comment_article.title }}</a>
            </li>
            {% endfor %}
        </ul>
        
    </div>
</div>

<script src='{% static "js/jquery.js" %}'></script>
<script src='{% static "editor/lib/marked.min.js" %}'></script>
<script src='{% static "editor/lib/prettify.min.js" %}'></script>
<script src='{% static "editor/lib/raphael.min.js" %}'></script>
<script src='{% static "editor/lib/underscore.min.js" %}'></script>
<script src='{% static "editor/lib/sequence-diagram.min.js" %}'></script>
<script src='{% static "editor/lib/flowchart.min.js" %}'></script>
<script src='{% static "editor/lib/jquery.flowchart.min.js" %}'></script>
<script src='{% static "editor/editormd.js" %}'></script>
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script>
<script type="text/javascript">

    $(function () {
        editormd.markdownToHTML("editormd-view", {
            htmlDecode: "style, script, iframe",
            emoji: true,
            taskList: true,
            tex: true,
            flowChart: true,
            sequenceDiagram: true,
        });
    });

    function like_article(id, action) {
        $.ajax({
            url: "{% url 'article:like_article' %}",
            type: "POST",
            data: {
                "id": id,
                "action": action
            },
            success: function (e) {
                if (e == "1") {
                    layer.msg("Thanks for your like.");
                    window.location.reload();
                } else {
                    layer.msg("I'll keep working on it.");
                    window.location.reload();
                }
            },
        });
    }

</script>

{% endwith %}
{% endblock %}

HelloCook/templates/article/list/article_titles.html
{% extends "base.html" %}
{% load article_tags %}
{% block title %} articles {% endblock %}
{% block content %}

<style>
    .button {
        background-color: white;
        color: black;
        border: 0.5px solid #008CBA;
        width: 100%;
        text-align: center;
        font-size: 28px;
    }

    .button:hover {
        background-color: #008CBA;
        color: white;
    }
</style>

<div class="row text-center vertical-middle-sm">
    <h2>Enjoy cooking, enjoy life!</h2>
    <h4>We have {% total_articles %} articles for you.</h4>
</div>
<br>
<br>
<div class="container">
    {% for article in articles %}
    <div class="list-group">

        <a href="{{article.get_url_path}}" class="list-group-item active">
            <button class="button" style="vertical-align:middle">
                {{article.title}}
            </button>
        </a>
        <h4 class="list-group-item-text">Author: <a
                href="{% url 'article:author_articles' article.author.username %}">{{article.author.username}}</a></h4>

        <p class="list-group-item-text">Abstract: {{article.abstract}}</p>
        <br>

    </div>
    {% endfor %}
    {% include "paginator.html" %}
</div>
{% endblock %}

HelloCook/templates/article/list/author_articles.html
{% extends "base.html" %}
{% load article_tags %}
{% load staticfiles %}
{% block title %}articles{% endblock %}
{% block content %}

<style>
    .button {
        background-color: white;
        color: black;
        border: 0.1px #008CBA;
        width: 100%;
        text-align: center;
        font-size: 28px;
    }

    .button:hover {
        background-color: #008CBA;
        color: white;
    }
</style>

<div class="row text-center vertical-middle-sm">
    <h2>Enjoy cooking, enjoy life!</h2>
</div>
<br>
<br>

<div class="container">
    <div class="col-md-8">
        {% for article in articles %}
        <div class="list-group">

            <a href="{{article.get_url_path}}" class="list-group-item active">
                <button class="button" style="vertical-align:middle">
                    {{article.title}}
                </button>
            </a>
            {% comment %} <h4 class="list-group-item-text">Author: <a
                    href="{% url 'article:author_articles' article.author.username %}">{{article.author.username}}</a>
            </h4> {% endcomment %}

            <h4 class="list-group-item-text">Abstract: {{article.abstract}}</h4>
            <br>

        </div>
        {% endfor %}
        {% include "paginator.html" %}
    </div>

    <div class="col-md-4">
        <div>
            {% if userinfo.photo %}
            <img src="{{ userinfo.photo | striptags }}" class="img-circle" id="my_photo" name="user_face"
                style="width: 300px">
            {% else %}
            <img name="user_face" src="{% static 'images/img1.jpg' %}" class="img-circle" id="my_photo"
                style="width: 300px">
            {% endif %}
        </div>
        <br>
        <div>
            <p>{{ user.username }}</p>
            <p>{% author_total_articles user %} articles published</p>
            {% if userinfo %}
            <p>{{ userinfo.company }}</p>
            <p>{{ userinfo.aboutme }}</p>
            {% else %}
            <p></p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

HelloCook/templates/article/list/latest_articles.html
<ul>
    {% for article in latest_articles %}
    <li>
        <a href="{{ article.get_url_path }}">{{ article.title }}</a>
    </li>
    {% endfor %}
</ul>

HelloCook/templates/article/list/most_liked_articles.html
<ul>
    {% for article in most_liked_articles %}
    <li>
        <a href="{{ article.get_url_path }}">{{ article.title }}</a>
    </li>
    {% endfor %}
</ul>

HelloCook/templates/article/list/most_viewed_articles.html
<ul>
    {% for article in most_viewed_articles %}
    <li>
        <a href="{{ article.get_url_path }}">{{ article.title }}</a>
    </li>
    {% endfor %}
</ul>