HelloCook/HelloCook/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from HelloCook import views
from django.views.generic import TemplateView

urlpatterns = [
    # path('', views.index, name='index'),
    path('', TemplateView.as_view(template_name="home.html"), name='home'),
    path('home/', TemplateView.as_view(template_name="home.html"), name='home'), 
    path('account/', include('account.urls')),
    path('article/', include('article.urls')),
    path('admin/', admin.site.urls),
]

HelloCook/account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'  

urlpatterns = [
    # path(r'login/', views.user_login, name='user_login'),
    path(r'login/', auth_views.LoginView.as_view(template_name="account/login.html"), name='user_login'),  # Use Django's built-in login methods
    path(r'loginout/', auth_views.LogoutView.as_view(template_name="account/logout.html"), name='user_logout'),  # Use Django's built-in logout methods
    path(r'register/', views.user_register, name='user_register'),
    path('password-change/', auth_views.PasswordChangeView.as_view(template_name="account/password_change_form.html",
        success_url="/account/password-change-done/"), name='password_change'),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(
        template_name="account/password_change_done.html"), name='password_change_done'),
    path('my-information/', views.myself, name='my_information'),
    path('edit-my-information/', views.myself_edit, name="edit_my_information"),
    path('my-image/', views.my_image, name="my_image"),
]

HelloCook/article/urls.py
from django.urls import path
from . import views, list_views
from django.urls import re_path

app_name = 'article'  

urlpatterns = [
    path('article-column/', views.article_column, name="article_column"),
    path('rename-article-column/', views.rename_article_column, name="rename_article_column"),
    path('del-article-column/', views.del_article_column, name="del_article_column"),
    path('article-post/', views.article_post, name="article_post"),
    path('article-list/', views.article_list, name="article_list"),
    re_path('article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"),
    path('del-article/', views.del_article, name="del_article"),
    path('redit-article/<int:article_id>/', views.redit_article, name="redit_article"),
    path('list-article-titles/', list_views.article_titles, name="article_titles"),
    path('article-content/<int:id>/<slug:slug>/', list_views.article_detail, name="article_content"),
    path('list-article-titles/<username>/', list_views.article_titles, name="author_articles"),
    path('like-article/', list_views.like_article, name="like_article"),
    path('view-article/', list_views.view_article, name="view_article"),
]

HelloCook/article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from slugify import slugify


class ArticleColumn(models.Model):
    user = models.ForeignKey(User, related_name='article_column', on_delete=models.CASCADE)
    column = models.CharField(max_length=200)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.column


class ArticlePost(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="article")
    title = models.CharField(max_length=200)
    abstract = models.CharField(max_length=200)
    slug = models.SlugField(max_length=500)
    column = models.ForeignKey(ArticleColumn, on_delete=models.CASCADE, related_name="article_column")
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    users_like = models.ManyToManyField(User, related_name="articles_like", blank=True)
    users_view = models.ManyToManyField(User, related_name="articles_view", blank=True)

    class Meta:
        ordering = ("-updated",)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.title

    def save(self, *args, **kargs):
        self.slug = slugify(self.title)
        super(ArticlePost, self).save(*args, **kargs)

    def get_absolute_url(self):
        return reverse("article:article_detail", args=[self.id, self.slug])

    def get_url_path(self):
        return reverse("article:article_content", args=[self.id, self.slug])

class Comment(models.Model):
    article = models.ForeignKey(ArticlePost, on_delete=models.CASCADE, related_name="comments")
    commentator = models.CharField(max_length=90)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return "Comment by {0} on {1}".format(self.commentator.username, self.article)

HelloCook/article/forms.py
from django import forms
from .models import ArticleColumn
from .models import ArticlePost
from .models import Comment


class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ("column",)

class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ("title", "abstract", "body")

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("commentator", "body",)

HelloCook/article/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from .models import ArticleColumn
from .forms import ArticleColumnForm
from .forms import ArticlePostForm
from django.views.decorators.http import require_POST
from .models import ArticlePost, Comment
from .forms import CommentForm
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


@login_required(login_url='/account/login/')
@csrf_exempt
def article_column(request):
    if request.method == "GET":
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form = ArticleColumnForm()
        return render(request, "article/column/article_column.html", {"columns": columns, 'column_form': column_form})

    if request.method == "POST":
        column_name = request.POST['column']
        columns = ArticleColumn.objects.filter(user_id=request.user.id, column=column_name)
        if columns:
            return HttpResponse('2')
        else:
            ArticleColumn.objects.create(user=request.user, column=column_name)
            return HttpResponse("1")


@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def rename_article_column(request):
    column_name = request.POST["column_name"]
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.column = column_name
        line.save()
        return HttpResponse("1")
    except:
        return HttpResponse("0")


@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article_column(request):
    column_id = request.POST["column_id"]
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")


@login_required(login_url='/account/login')
@csrf_exempt
def article_post(request):
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data
            try:
                new_article = article_post_form.save(commit=False)
                new_article.author = request.user
                new_article.column = request.user.article_column.get(id=request.POST['column_id'])
                new_article.save()
                return HttpResponse("1")
            except:
                return HttpResponse("2")
        else:
            return HttpResponse("3")
    else:
        article_post_form = ArticlePostForm()
        article_columns = request.user.article_column.all()
        return render(request, "article/column/article_post.html",
                      {"article_post_form": article_post_form, "article_columns": article_columns})


@login_required(login_url='/account/login')
def article_list(request):
    articles_list = ArticlePost.objects.filter(author=request.user)
    paginator = Paginator(articles_list, 10)
    page = request.GET.get('page')
    try:
        current_page = paginator.page(page)
        articles = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
        articles = current_page.object_list
    return render(request, "article/column/article_list.html", {"articles": articles, "page": current_page})


# @login_required(login_url='/account/login')
# def article_detail(request, id, slug):
#     article = get_object_or_404(ArticlePost, id=id, slug=slug)
#     return render(request, "article/column/article_detail.html", {"article": article})


@login_required(login_url='/account/login')
def article_detail(request, id, slug):
    article = get_object_or_404(ArticlePost, id=id, slug=slug)

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.article = article
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, "article/list/article_content.html",
                  {"article": article, "comment_form": comment_form})


@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article(request):
    article_id = request.POST['article_id']
    try:
        article = ArticlePost.objects.get(id=article_id)
        article.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")


@login_required(login_url='/account/login')
@csrf_exempt
def redit_article(request, article_id):
    if request.method == "GET":
        article_columns = request.user.article_column.all()
        article = ArticlePost.objects.get(id=article_id)
        this_article_form = ArticlePostForm(initial={"title": article.title})
        this_article_column = article.column
        return render(request, "article/column/redit_article.html",
                      {"article": article, "article_columns": article_columns, "this_article_column": this_article_column, "this_article_form": this_article_form})
    else:
        redit_article = ArticlePost.objects.get(id=article_id)
        try:
            redit_article.column = request.user.article_column.get(id=request.POST['column_id'])
            redit_article.title = request.POST['title']
            redit_article.abstract = request.POST['abstract']
            redit_article.body = request.POST['body']
            redit_article.save()
            return HttpResponse("1")
        except:
            return HttpResponse("2")

HelloCook/templates/article/column/article_column.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}article column{% endblock %}
{% block content %}
<div>
    <p class="text-right">
        <button id="add_column" onclick="add_column()" class="btn btn-primary"> add column</button>
    </p>
    <table class="table table-hover">
        <tr>
            <td>Index</td>
            <td>Column</td>
            <td>Operation</td>
        </tr>
        {% for column in columns %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ column.column }}</td>
            <td>
                <a name="edit" href="javascript:" onclick="edit_column(this, {{ column.id }})"> <span
                        class="glyphicon glyphicon-pencil"></span></a>
                <a name="delete" href="javascript:" onclick="del_column(this, {{ column.id }})"><span
                        class="glyphicon glyphicon-trash" style="margin-left:20px;"></span></a>
            </td>
        </tr>
        {% empty %}
        <p>Start by adding a column.</p>
        {% endfor %}
    </table>
</div>

<script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script>
<script type="text/javascript">
    function add_column() {
        var index = layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            title: "Add new column",
            content: '<div class="text-center" style="margin-top:20px"><p> Please enter name of new column </p><p>{{ column_form.column }}</p></div>',
            btn: ['YES', 'NO'],
            yes: function (index, layero) {
                column_name = $('#id_column').val();
                $.ajax({
                    url: '{% url "article:article_column" %}',
                    type: 'POST',
                    data: {
                        "column": column_name
                    },
                    success: function (e) {
                        if (e == "1") {
                            parent.location.reload();
                            layer.msg("good");
                        } else {
                            layer.msg("Name repeated, please change name.")
                        }
                    },
                });
            },
            btn2: function (index, layero) {
                layer.close(index);
            }
        });
    }

    function edit_column(the, column_id) {
        var name = $(the).parents("tr").children("td").eq(1).text();
        var index = layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            title: "Edit column",
            content: '<div class="text-center" style="margin-top:20px"> <p> Please enter name of new colum </p><p><input type="text" id="new_name" value="' +
                name + '"></p> </div>',
            btn: ['YES', 'NO'],
            yes: function (index, layero) {
                new_name = $("#new_name").val();
                $.ajax({
                    url: "{% url 'article:rename_article_column' %}",
                    type: "POST",
                    data: {
                        "column_id": column_id,
                        "column_name": new_name
                    },
                    success: function (e) {
                        if (e == "1") {
                            parent.location.reload();
                            layer.msg("good");
                        } else {
                            layer.msg("failed")
                        }
                    },
                });
            },
        });
    }
    
    function del_column(the, column_id){
        var name = $(the).parents("tr").children("td").eq(1).text();
        layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            title: "Delete column",
            content: '<div class="text-center" style="margin-top:20px"><p>Are you sure to delete column {'+name+'} ?</p> </div>',
            btn:['YES', NO], yes: function(){
                $.ajax({
                    url: '{% url "article:del_article_column" %}',
                    type:"POST",
                    data: {"column_id":column_id},
                    success: function(e){
                        if(e=="1"){
                            parent.location.reload();
                            layer.msg("has been deleted.");
                        }else{
                            layer.msg("delete failed");
                        }
                    },
                })
            },
        });
    }
</script>
{% endblock %}

HelloCook/templates/article/column/article_detail.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %} articles list {% endblock %}
{% block content %}

<div>
    <header>
        <h1>{{ article.title }}</h1>
        <h4>Abstract: {{ article.abstract }}</h3>
        <p>Author: {{ user.username }}</p>
    </header>

    <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}" />
    <div id='editormd-view'>
        <textarea id="append-test" style="display:none;">
{{ article.body }}
        </textarea>
    </div>
</div>

<script src='{% static "js/jquery.js" %}'></script>
<script src='{% static "editor/lib/marked.min.js" %}'></script>
<script src='{% static "editor/lib/prettify.min.js" %}'></script>
<script src='{% static "editor/lib/raphael.min.js" %}'></script>
<script src='{% static "editor/lib/underscore.min.js" %}'></script>
<script src='{% static "editor/lib/sequence-diagram.min.js" %}'></script>
<script src='{% static "editor/lib/flowchart.min.js" %}'></script>
<script src='{% static "editor/lib/jquery.flowchart.min.js" %}'></script>
<script src='{% static "editor/editormd.js" %}'></script>
<script type="text/javascript">
    $(function () {
        editormd.markdownToHTML("editormd-view", {
            htmlDecode: "style, script, iframe",
            emoji: true,
            taskList: true,
            tex: true,
            flowChart: true,
            sequenceDiagram: true,
        });
    });
</script>
{% endblock %}

HelloCook/templates/article/column/article_list.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}articles list{% endblock %}
{% block content %}
<div>
    <table class="table table-hover">
        <tr>
            <td>Index</td>
            <td>Title</td>
            <td>Column</td>
            <td>Operation</td>
        </tr>
        {% for article in articles %}
        <tr id={{ article.id }}>
            <td>{{ forloop.counter }}</td>
            <td><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></td>
            <td>{{ article.column }}</td>
            <td>
                <a name="edit" href="{% url 'article:redit_article' article.id %}"><span
                        class="glyphicon glyphicon-pencil"></span></a>
                <a nane="delete" href="javascript:" onclick="del_article(this, {{ article.id }})"><span
                        class="glyphicon glyphicon-trash" style="margin-left:20px;"></span></a>
            </td>
        </tr>
        {% endfor %}
    </table>
    {% include "paginator.html" %}
</div>
<script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script>
<script type="text/javascript">
    function del_article(the, article_id) {
        var article_name = $(the).parents("tr").children("td").eq(1).text();
        layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            title: "Deletearticle",
            content: '<div class="text-center" style="margin-top:20px"><p>Are you sure to delete《' + article_name +
                '》?</p> </div>',
            btn: ['YES', 'NO'],
            yes: function () {
                $.ajax({
                    url: '{% url "article:del_article" %}',
                    type: "POST",
                    data: {
                        "article_id": article_id
                    },
                    success: function (e) {
                        if (e == "1") {
                            parent.location.reload();
                            layer.msg("has been deleted.");
                        } else {
                            layer.msg("delete failed.");
                        }
                    },
                })
            },
        });
    }
</script>
{% endblock %}

HelloCook/templates/article/column/article_post.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %} article column {% endblock %}
{% block content %}

<link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
<link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">

<div style="margin-left:10px">
    <form class="form-horizontal" action="." method="post">{% csrf_token %}
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>Title:</span></div>
            <div class="col-md-10 text-left">{{article_post_form.title}}</div>
        </div>
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>Column:</span></div>
            <div class="col-md-10 text-left">
                <select id="which_column">
                    {% for column in article_columns %}
                    <option value="{{column.id}}">{{column.column}}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>Abstract:</span></div>
            <div class="col-md-10 text-left">{{article_post_form.abstract}}</div>
        </div>
        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>Content:</span></div>
            <div id="editormd" class="col-md-10 text-left">
                <textarea style="display:none;" id="id_body"></textarea>
            </div>
        </div>
        <div class="row">
            <input type="button" class="btn btn-primary btn-lg" value="Publish" onclick="publish_article()">
        </div>
    </form>
</div>

<script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
<script type="text/javascript" src='{% static "js/layer.js" %}'></script>
<script type="text/javascript">
    function publish_article() {
        var title = $("#id_title").val();
        var abstract = $("#id_abstract").val();
        var column_id = $("#which_column").val();
        var body = $("#id_body").val();
        var article_tags = [];
        $.each($("input[name='article_tag']:checked"), function () {
            article_tags.push($(this).val());
        });
        $.ajax({
            url: "{% url 'article:article_post' %}",
            type: "POST",
            data: {
                "title": title,
                "abstract": abstract,
                "body": body,
                "column_id": column_id,
                "tags": JSON.stringify(article_tags)
            },
            success: function (e) {
                if (e == "1") {
                    //layer.msg("successful");
                    location.href = "{% url 'article:article_list' %}"; 
                } else if (e == "2") {
                    layer.msg("sorry.");
                } else {
                    layer.msg("Content can not be empty。");
                }
            },
        });
    }
</script>
<script type="text/javascript" src='{% static "editor/editormd.min.js" %}'></script>
<script type="text/javascript">
    $(function () {
        var editor = editormd("editormd", {
            width: "100%",
            height: 640,
            syncScrolling: "single",
            path: "{% static 'editor/lib/' %}"
        });
    });
</script>

{% endblock %}

HelloCook/templates/article/column/redit_article.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %}article column{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
<link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">
<div class="container">
    <div class="col-md-10">
        <div style="margin-left:10px">
            <form class="form-horizontal" action="." method="post">{% csrf_token %}
                <div class="row" style="margin-top: 10px;">
                    <div class="col-md-2 text-right"><span>Title:</span></div>
                    <div class="col-md-10 text-left">{{this_article_form.title}}</div>
                </div>
                <div class="row" style="margin-top: 10px;">
                    <div class="col-md-2 text-right"><span>Column:</span></div>
                    <div class="col-md-10 text-left">
                        <select id="which_column">
                            {% for column in article_columns %}
                            {% if column == this_article_column.column %}
                            <option value="{{column.id}}" selected="selected">{{column.column}}</option>
                            {% else %}
                            <option value="{{column.id}}">{{column.column}}</option>

                            {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="row" style="margin-top: 10px;">
                    <div class="col-md-2 text-right"><span>Content:</span></div>
                    <div id="editormd" class="col-md-10 text-left">
                        <!--{{article_post_form.body}}-->
                        <textarea style="display:none;" id="id_body">
{{article.body}}
                </textarea>
                    </div>
                </div>
                <div class="row">
                    <input type="button" class="btn btn-primary btn-lg" value="Done" onclick="redit_article()">
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
<script type="text/javascript" src='{% static "editor/editormd.min.js" %}'></script>
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script>
<script type="text/javascript">
    $(function () {
        var editor = editormd("editormd", {
            width: "100%",
            height: 640,
            //syncScrolling : "single",
            path: "{% static 'editor/lib/' %}",
        });
    });
</script>

<script type="text/javascript">
    function redit_article() {
        var title = $("#id_title").val();
        var column_id = $("#which_column").val();
        var body = $("#id_body").val();
        $.ajax({
            url: "{% url 'article:redit_article' article.id %}",
            type: "POST",
            data: {
                "title": title,
                "body": body,
                "column_id": column_id
            },
            success: function (e) {
                if (e == "1") {
                    layer.msg("successful");
                    location.href = "{% url 'article:article_list' %}";
                } else {
                    layer.msg("sorry.");
                }
            },
        });
    }
</script>

{% endblock %}